### ISSUE TITLE
layered.c test not working as intended?

### ISSUE THREAD

**Issue by iSplasher** [datenwolf/wglarb#1]
Hi, I followed here from your stackoverflow answer and tried setting up the layer.c test.
When I apply `WS_POPUP` to the window, nothing shows up when I run.
Any ideas as to why this is happening?

**Comment by datenwolf** [comment]
Do you run Windows 8 or Windows 10? Microsoft did some radical changes to Aero semantics. Since there's no longer a blurring effect `DwmBlurBehindWindow` works differently. I simply haven't gotten around yet, to figure out the right combination of parameters (window ex-/style, DWM settings) to reenable the effect on Win8 and later.

**Comment by iSplasher** [comment]
Thanks for the fast response.
I'm running on Windows 10 build 1803.
I'll look into it.
Which OS were you running it on?

**Comment by datenwolf** [comment]
I wrote this on a Windows-7 machine. Heck by private box still runs on Win-7 despite its support being ceased. If Microsoft did offer some Win-10 LTSB for Joe average, I'd have long upgraded (I have Win-10 LTSB available and installed at work); the "standard" versions are just annoyingly bloated with stuff I don't want.

**Comment by iSplasher** [comment]
That's unfortunate...
I was intending to use this trick to create a window that displayed only the rendered content, allowing a 3d model to be displayed on the desktop looking as if it has no window associated with it, if that makes sense.

**Comment by datenwolf** [comment]
Technically it should still be possible to do. I just haven't figured out the right combination of parameters, though. It will likely require a decorationless window (no titlebar, no borders), i.e. plain WM_POPUP and a certain combination of DwmBlur… parameters.

**Comment by iSplasher** [comment]
Okay thank you for your time!
If ever you get time to take a look at it, please let me know if you still remember me.
